feat: PI-203 support for hagall integration test
aukilabs/hagall-common pull request #3
Opened 2024-02-27 04:55 UTC by keeal

https://auki.atlassian.net/browse/PI-203

This PR is to add supports for hagall integration tests

2024-02-27 05:47 UTC, omusil24 requested changes

2024-02-27 05:47 UTC, omusil24 commented on scenariorunner/scenario/integrationtest.go
> +	logs.Debug("starting integration test")
The logs here and on line 35 can be Info instead of Debug, no?

2024-02-27 06:28 UTC, omusil24 approved these changes, later dismissed

2024-02-28 03:32 UTC, omusil24 submitted a review, later dismissed

2024-02-28 06:36 UTC, omusil24 approved these changes

2024-02-28 08:25 UTC, dataviruset approved these changes

2024-02-28 08:53 UTC, merged