feat: add signed ping request message
aukilabs/hagall-common pull request #7
Opened 2024-03-19 08:45 UTC by tatiesmars

- update protoc

2024-03-19 09:41 UTC, omusil24 approved these changes, later dismissed
Fine by me. @keeal ?

2024-03-19 11:31 UTC, tatiesmars commented
added data structure for the message

2024-03-19 13:15 UTC, omusil24 requested changes

2024-03-19 13:15 UTC, omusil24 commented on messages/hagallpb/hagall.proto
> +  MSG_TYPE_SIGNED_PING_REQUEST = 42;
Should this actually be "latency" instead of ping?

2024-03-19 13:15 UTC, omusil24 commented on messages/hagallpb/hagall.proto
> +  uint32 number_of_iteration = 3;
This would be better named `iteration_count`.

2024-03-19 13:15 UTC, omusil24 commented on messages/hagallpb/hagall.proto
> +  string sig = 4;
This can be named `signature`, no?

2024-03-19 13:15 UTC, omusil24 commented on messages/hagallpb/hagall.proto
> +  string address = 8;
This should be `wallet_address`.

2024-03-20 06:26 UTC, omusil24 approved these changes, later dismissed

2024-03-20 09:33 UTC, omusil24 approved these changes

2024-03-20 09:42 UTC, keeal commented on messages/hagallpb/hagall.proto
> +  LatencyData data = 3;
should this be bytes / string that contains the marshalled LatencyData? since signature is the product of signing this field.

2024-03-21 02:27 UTC, tatiesmars commented on messages/hagallpb/hagall.proto
> +  LatencyData data = 3;
LatencyData in the protobuf message is equal to marshal LatencyData.

2024-03-27 04:57 UTC, shuning-auki approved these changes

2024-03-28 03:11 UTC, merged